### ISSUE TITLE
Make Arroyo consistent in the usage of the Message object

### ISSUE THREAD

**Issue by fpacifici** [getsentry/arroyo#125]
There are two competing requirements in how processing strategies are designed. These are emerging from real world usages of the API.
On one hand, there are designs where there is a 1:1 relationship between messages seen by a `ProcessingStrategy` and messages produced by Kafka. The payload may have been altered but the Message still contains a meaningful partition and offset. The snuba consumer works like this
On the other hand there are designs where new messages are created in the pipeline that do not have a direct correspondence to an individual Kafka message. An example is the batching step in the Metrics Indexer. It accumulates messages into a batch and send the batch as a message to the next step. In this case the Batch, which has to be represented as a message, does not have a corresponding meaningful Kafka partition and offset.

The interface we have today seems to be designed for the first use case and does not work for the second.
This has implications:
- We cannot have a clean representation of a pipeline that contains aggregation steps or steps that introduce new messages as these cannot be associated to an individual Kafka message. Or if they do, that association has no meaning. This is troublesome as batching steps tend to be very useful. 
- Following the first approach means we cannot modularize pipeline as a sequence of steps that much. Any step that performs batching needs to encapsulate all the following steps if it wants to stick to the ProcessingStrategy API correctly. This is because it cannot assign an offset to a Batch. 
- This is the reason the existing CollectStep is so cumbersome. 

I think we need to make a decision about how to modularize our pipelines and stick to it:
- If we want to stick to the current interface: "a processing strategy takes a Message that has a valid partition and offset", then we cannot compose pipelines by introducing steps that batch messages and forward a batch to the following step. This means we need to introduce a different composition mechanism that works at a different abstraction level so that we can still express pipelines as `transform`, `filter`, `batch`.
- If we want to properly break this constraint and allow steps to forward batches, then the `submit` interface needs to change to accommodate the case where we forward a message that does not correspond to an individual Kafka message.

In alternative we can give up on the idea to provide batching features out of the box and let the client implement their own solution. I would advise against this as it is such a common and useful features. A ton of use cases rely on batching in some way, adding friction for the customer that wants to use it would defy the purpose of the api which is to make the right thing easy.

**Comment by lynnagara** [comment]
Thanks for this write up. Today the `submit` interface is not really designed to support batching. We sometimes make it work but we do so by awkwardly working around some constraints. Today processing strategies expect a `Message` with a singular partition, offset and timestamp, which generally corresponds one to one with a Kafka message. This breaks down anytime we need to do batch operations (which is often). In that case what is received by a processing step can span multiple partitions with different offsets and timestamps for each.

The only real reason why Message always needs to contain this information is for committing offsets, which generally always happens at the end of every processing step, so that we only commit after successful processing. But this means all that partition and offset information needs to be passed all the way through every step.

To me, the most straightforward solution would be to allow each message to know the watermark across multiple partitions.

For example, we could replace what we have now:
```
class Message(Generic[TPayload]):
    partition: Partition
    offset: int
    payload: TPayload
    timestamp: datetime
```
with something along the lines of
```
class Message(Generic[TPayload]):
    committable: Mapping[Partition, Position]
    payload: TPayload
```
so that each message can commit across multiple partitions.

If we decide to go with some new structure like this, I think migrating is going to be a bit of a challenge. This is very much going to be a breaking change since it is main interface of the processing steps which is the main part that users need to provide.

**Comment by fpacifici** [comment]
> The only real reason why Message always needs to contain this information is for committing offsets, which generally always happens at the end of every processing step, so that we only commit after successful processing.

I think this is an interesting point.
If we actually consider offset and partition a library concern and not something the application should care about, we could make the commit process even more opaquer to the application developer. Which would probably be positive as it is error prone.  The commit function we pass could just take the message object and figure out which offsets to stage and when to actually commit. 
I think there are a few questions to address first:
- It is not 100% true that we rely on offset and partition only to commit. We log them at times (but this is not a blocker), and we produce the offset and the partition on the commit log  in the consumer with commit log. So there is at least one application use. We could make the commit log transparent though and make it managed by the library. Though the post process forwarder still compares offsets and partitions. 
- Out of order processing. This is uncommon today (probably we never do that) but it will become more likely the more use case we onboard. It would be already desirable for the replays consumer where we have fast messages and slow messages. To preserve the guarantee of delivery, no matter the order messages are processed in, we still need to be sure that, before committing an offset, all the previous ones are processed. Today, in order to achieve this, the application would have to keep track of the seen offsets and of the processed ones so it can keep track of a watermark. This as well would have to be built into the library.

**Comment by lynnagara** [comment]
I think the underlying reason why this problem arises is because the `Message` object serves two distinct purposes:

1. It's the interface of every processing step. Here the partition/offset/timestamp properties don't always make sense since a message may no longer represent a singular message received from the broker. We have to force messages into this format even though it doesn't make a lot of sense for filter/batching steps where a message may not map to one consumer message anymore.
2. `Message` is also the interface of the message received from the broker. In this case there is always a single offset, timestamp and partition and this interface makes sense here.

I believe the solution to this is to actually split `Message` in two so that we can better serve the two distinct purposes. I think that what we get from the consumer should always still has the offset, timestamp and partition, but what we pass to each strategy does not need to have these properties but just has the `Mapping[Partition, Position]` part for committing which can then span many partitions. The first processing step will always get the first type of message but subsequent ones only need to get the second. Of course, if the message data is needed for something else the user is still free to pass it through to subsequent steps but this only happens if it's needed for the logic of that specific consumer.

I think the main downside of this approach would be that the implementation would likely require us to keep an extra piece of information on every message we get from the broker in some cases (i.e those where we are only ever dealing with individual messages and not batches). I think this is a reasonable trade off to make in order for the `ProcessingStep` interface to make sense when we are doing things like filter and batch which break the 1:1 relationship of processing step messages and Kafka messages.

**Comment by lynnagara** [comment]
Addressed in https://github.com/getsentry/arroyo/pull/134
